# -*- coding: utf-8 -*-
"""PYTORCH TRANSFER LEARNING.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jzr6zkLy5pXfWHzxIRuf5jgkGTvJSfKk

# 06. PyTorch Transfer Learning

> **Note:** This notebook uses `torchvision`'s new [multi-weight support API (available in `torchvision` v0.13+)](https://pytorch.org/blog/introducing-torchvision-new-multi-weight-support-api/).

We've built a few models by hand so far.

But their performance has been poor.

You might be thinking, **is there a well-performing model that already exists for our problem?**

And in the world of deep learning, the answer is often *yes*.

We'll see how by using a powerful technique called [**transfer learning**](https://developers.google.com/machine-learning/glossary#transfer-learning).

## What is transfer learning?

**Transfer learning** allows us to take the patterns (also called weights) another model has learned from another problem and use them for our own problem.

For example, we can take the patterns a computer vision model has learned from datasets such as [ImageNet](https://www.image-net.org/) (millions of images of different objects) and use them to power our FoodVision Mini model.

Or we could take the patterns from a [language model](https://developers.google.com/machine-learning/glossary#masked-language-model) (a model that's been through large amounts of text to learn a representation of language) and use them as the basis of a model to classify different text samples.

The premise remains: find a well-performing existing model and apply it to your own problem.

<img src="https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/06-transfer-learning-example-overview.png" alt="transfer learning overview on different problems" width=900/>

*Example of transfer learning being applied to computer vision and natural language processing (NLP). In the case of computer vision, a computer vision model might learn patterns on millions of images in ImageNet and then use those patterns to infer on another problem. And for NLP, a language model may learn the structure of language by reading all of Wikipedia (and perhaps more) and then apply that knowledge to a different problem.*

## Where to find pretrained models

The world of deep learning is an amazing place.

So amazing that many people around the world share their work.

Often, code and pretrained models for the latest state-of-the-art research is released within a few days of publishing.

And there are several places you can find pretrained models to use for your own problems.

| **Location** | **What's there?** | **Link(s)** |
| ----- | ----- | ----- |
| **PyTorch domain libraries** | Each of the PyTorch domain libraries (`torchvision`, `torchtext`) come with pretrained models of some form. The models there work right within PyTorch. | [`torchvision.models`](https://pytorch.org/vision/stable/models.html), [`torchtext.models`](https://pytorch.org/text/main/models.html), [`torchaudio.models`](https://pytorch.org/audio/stable/models.html), [`torchrec.models`](https://pytorch.org/torchrec/torchrec.models.html) |
| **HuggingFace Hub** | A series of pretrained models on many different domains (vision, text, audio and more) from organizations around the world. There's plenty of different datasets too. | https://huggingface.co/models, https://huggingface.co/datasets |
| **`timm` (PyTorch Image Models) library** | Almost all of the latest and greatest computer vision models in PyTorch code as well as plenty of other helpful computer vision features. | https://github.com/rwightman/pytorch-image-models|
| **Paperswithcode** | A collection of the latest state-of-the-art machine learning papers with code implementations attached. You can also find benchmarks here of model performance on different tasks. | https://paperswithcode.com/ |

<img src="https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/06-transfer-learning-where-to-find-pretrained-models.png" alt="different locations to find pretrained neural network models" width=900/>

*With access to such high-quality resources as above, it should be common practice at the start of every deep learning problem you take on to ask, "Does a pretrained model exist for my problem?"*

> **Exercise:** Spend 5-minutes going through [`torchvision.models`](https://pytorch.org/vision/stable/models.html) as well as the [HuggingFace Hub Models page](https://huggingface.co/models), what do you find? (there's no right answers here, it's just to practice exploring)

## 1. Make predictions on the entire test dataset and plot a confusion matrix for the results of our model compared to the truth labels.
* **Note:** You will need to get the dataset and the trained model/retrain the model from notebook 06 to perform predictions.
* Check out [03. PyTorch Computer Vision section 10](https://www.learnpytorch.io/03_pytorch_computer_vision/#10-making-a-confusion-matrix-for-further-prediction-evaluation) for ideas.
"""

import numpy
print(numpy.__version__)
!pip install --upgrade --force-reinstall numpy

import numpy as np
print(np.__version__)

# Download the torchinfo liberary
try:
  from torchinfo import summary
except:
  !pip install torchinfo
  from torchinfo import summary

# Download the helper functions
try:
  from going_modular import data_setup, engine
except :
  !git clone https://github.com/mrdbourke/pytorch-deep-learning
  !mv pytorch-deep-learning/going_modular/going_modular .
  !rm -rf pytorch-deep-learning
  from going_modular import data_setup, engine

from going_modular import data_setup, engine

# Set up the device agnostice code
import torch
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

"""### Get Data"""

import os
import torchvision
import requests
from pathlib import Path
import zipfile
import matplotlib.pyplot as plt

data_path = Path('data/')
image_path = data_path/'pizza_steak_sushi'
image_path_zip = data_path/'pizza_steak_sushi.zip'

if image_path.is_dir():
  print(f'{image_path} already exist. Skipping the download.')
else:
  image_path.mkdir(parents = True, exist_ok = True)
  with open(image_path_zip, 'wb') as f:
    request = requests.get('https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/data/pizza_steak_sushi.zip')
    print(f'Download {image_path_zip}')
    f.write(request.content)
  with zipfile.ZipFile(image_path_zip, 'r') as zip_ref:
    print(f'Unzip pizza, steak, sushi data.')
    zip_ref.extractall(image_path)
  print(f'the Download done sucessefuly. ')
  os.remove(image_path_zip)
train_dir = image_path/'train'
test_dir = image_path/'test'

"""### Prepare data"""

from torchvision import transforms
# Create a simple transform
simple_transform = transforms.Compose([
    transforms.Resize(size=(224,224)),
    transforms.ToTensor(),
    transforms.Normalize(mean = [0.485,0.456,0.406],
                         std = [0.229,0.224,0.225])
])

# Create a dataloader
train_dataloader, test_dataloader, class_names = data_setup.create_dataloaders(train_dir = train_dir,
                                                                               test_dir = test_dir,
                                                                               transform = simple_transform,
                                                                               batch_size = 32)
train_dataloader, test_dataloader, class_names

train_dataloader, test_dataloader, class_names = data_setup.create_dataloaders(train_dir = train_dir,
                                                                             test_dir = test_dir,
                                                                             batch_size = 32,
                                                                             transform = simple_transform)
train_dataloader, test_dataloader, class_names

"""### Get and prepare a pretrained model"""

# Set up the model with pretrained weights and send it to the target device
model_0 = torchvision.models.efficientnet_b0(pretrained = True).to(device)

# Loss function
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(params = model_0.parameters(), lr = 0.001)

"""### Train model"""

# Set the random seed
torch.cuda.manual_seed(42)
torch.manual_seed(42)
# Train time
from timeit import default_timer as timer
start_train = timer()
model_0_results = engine.train(model = model_0,
                    train_dataloader = train_dataloader,
                    test_dataloader  = test_dataloader,
                    loss_fn = loss_fn,
                    optimizer = optimizer,epochs = 5, device = device
      )
end_train = timer()
print(f'the model train for : {end_train - start_train:.3f}seconds')

"""### Make prediction on the entire dataset with the model"""

from tqdm.auto import tqdm
# Make prediction on the entire test_dataset
test_preds = []
model_0.eval()
with torch.inference_mode():
  for X,y in tqdm(test_dataloader):
    X,y = X.to(device), y.to(device)
    x_logits = model_0(X)
    pred_probs = torch.softmax(x_logits, dim=1)
    pred_labels = torch.argmax(pred_probs, dim=1)
    test_preds.append(pred_labels.cpu())
test_preds = torch.cat(test_preds)
test_preds

"""### Make confusion matrix with the test preds and the truth labels"""

# Get the truth labels for test dataset
test_truth = torch.cat([y for X,y in test_dataloader])
test_truth

#!pip install --upgrade --force-reinstall numpy

import numpy as np
print(f'The numpy version is : {np.__version__}')

try:
  import torchmetrics, mlxtend
  assert int(mlxtend.__version__.split('.')[1]) >= 19, 'torch_metrics version shoud be 0.19.0 or higher'
  print(mlxtend.__version__)
except:
  !pip install -q torchmetrics -U mlxtend
  import torchmetrics, mlxtend
  print(mlxtend.__version__)

# See if torchmetrics exist if not install it
try:
  import torchmetrics, mlxtend
  print(f'mlxtend version {mlxtend.__version__}')
  assert int(mlxtend.__version__.split('.')[1]) >= 19 , 'mlxtend version should be 0.19.0 or higher'
except:
  !pip install -q torchmetrics -U mlxtend
  import torchmetrics, mlxtend
  print(f'mlxtend version : {mlxtend.__version__}')

from torchmetrics import ConfusionMatrix
from mlxtend.plotting import plot_confusion_matrix

confmat = ConfusionMatrix(task='multiclass', num_classes = len(class_names))
confmat_tensor = confmat(preds = test_preds,
                         target = test_truth)
fig, ax = plot_confusion_matrix(
    conf_mat = confmat_tensor.numpy(),
    class_names = class_names,
    figsize = (10,6)
)

"""## 2. Get the "most wrong" of the predictions on the test dataset and plot the 5 "most wrong" images. You can do this by:
* Predicting across all of the test dataset, storing the labels and predicted probabilities.
* Sort the predictions by *wrong prediction* and then *descending predicted probabilities*, this will give you the wrong predictions with the *highest* prediction probabilities, in other words, the "most wrong".
* Plot the top 5 "most wrong" images, why do you think the model got these wrong?

You'll want to:
* Create a DataFrame with sample, label, prediction, pred prob
* Sort DataFrame by correct (does label == prediction)
* Sort DataFrame by pred prob (descending)
* Plot the top 5 "most wrong" image predictions
"""

from pathlib import Path
from PIL import Image
test_paths = list(Path(test_dir).glob('*/*.jpg'))
def predict_and_store(test_paths, model, class_names, transform, device):
  test_path_list = []
  for path in test_paths:
    pred_dict = {}
    pred_dict['image_path'] = path
    class_name = path.parent.stem
    pred_dict['class_name'] = class_name
    img = Image.open(path)
    transformed_image = transform(img).unsqueeze(dim=0).to(device)
    model.eval()
    with torch.inference_mode():
      x_logits = model(transformed_image)
      pred_prob = torch.softmax(x_logits, dim=1)
      pred_label = torch.argmax(pred_prob, dim=1)
      pred_dict['pred_prob'] = pred_prob.max().cpu().item()
      pred_dict['pred_label'] = class_names[pred_label]
      pred_dict['correct'] = class_name == class_names[pred_label]
    test_path_list.append(pred_dict)
  return test_path_list
test_pred_dicts = predict_and_store(test_paths,
                                    model_0,
                                    class_names,
                                    simple_transform,
                                    device)
test_pred_dicts[:5]

import pandas as pd
test_pred_df = pd.DataFrame(test_pred_dicts)
# Sort dataframe by correct then py pred_probs
top_5_most_wrong = test_pred_df.sort_values(['correct', 'pred_prob'], ascending = [True, False]).head()
top_5_most_wrong

#import torchvision
import matplotlib.pyplot as plt
from PIL import Image
for index, row in top_5_most_wrong.iterrows():
  image_path = row['image_path']
  true_label = row['class_name']
  pred_prob  = row['pred_prob']
  pred_label = row['pred_label']
  #img = torchvision.io.read_image(image_path)
  img = Image.open(image_path)
  plt.figure()
  plt.imshow(img)
  plt.title(f'True_label:{true_label}|Pred_label:{pred_label}|Pred_prob:{pred_prob:.3f}')
  plt.axis(False);

# Get an image of pizza/steak/sushi
!wget https://images.unsplash.com/photo-1588315029754-2dd089d39a1a
!cp photo-1588315029754-2dd089d39a1a pizza.jpg

from PIL import Image

with Image.open("pizza.jpg") as img:
  # Reduce the image size and width by 10
  (width, height) = (img.width // 10, img.height // 10)
  img_resized = img.resize((width, height))

img_resized

# make a fuction to pred and plot images
def predict_and_plot(image_path, class_name, model, transform, device = device):
  img = Image.open(image_path)
  transformed_image = transform(img)
  model.eval()
  with torch.inference_mode():
    x_logits = model(transformed_image.unsqueeze(0).to(device))
    pred_prob = torch.softmax(x_logits, dim=1)
    pred_label = torch.argmax(pred_prob, dim=1)
  plt.imshow(transformed_image.permute(1,2,0))
  plt.title(f'Pre_label:{class_name[pred_label]}|Pred_Prob:{pred_prob.max():.4f}')
  plt.axis(False);

predict_and_plot(image_path = 'pizza.jpg',
                 class_name = class_names,
                 model = model_0,
                 transform = simple_transform,
                 device = device)

# Try on a photo of apple
!wget https://images.unsplash.com/photo-1570913149827-d2ac84ab3f9a
!cp photo-1570913149827-d2ac84ab3f9a apple.jpg
predict_and_plot(image_path = 'apple.jpg',
                 model = model_0,
                 class_name = class_names,
                 transform = simple_transform)

!wget https://images.unsplash.com/photo-1570913149827-d2ac84ab3f9a
!cp photo-1570913149827-d2ac84ab3f9a apple_1.jpg
predict_and_plot(image_path = 'apple_1.jpg',
                 model = model_0,
                 class_name = class_names,
                 transform = simple_transform)

"""## 4. Train the model from section 4 above for longer (10 epochs should do), what happens to the performance?"""

import torchvision
from torch import nn
model_1 = torchvision.models.efficientnet_b0(pretrained = True).to(device)
# Freeze the base layer
for param in model_1.features.parameters():
  param.requires_grad = False
# Change the classifier head
torch.manual_seed(42)
model_1.classifier = nn.Sequential(
    nn.Dropout(p=0.2, inplace=True),
    nn.Linear(in_features=1280, out_features=len(class_names), bias=True)
)
summary(model = model_1, input_size = [32,3,224,224],
        col_names = ['input_size', 'output_size', 'trainable'])

# Set up the optimizer and the loss_fn
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(params = model_1.parameters(), lr = 0.001)

from timeit import default_timer as timer
# train the model_1
torch.cuda.manual_seed(42)
torch.manual_seed(42)
start_train = timer()
model_1_results = engine.train(model = model_1,
                              train_dataloader = train_dataloader,
                              test_dataloader = test_dataloader,
                              optimizer = optimizer,
                              loss_fn = loss_fn,
                              epochs = 10,
                              device = device)
end_train = timer()
print(f'The model was training for : {end_train - start_train} seconds.')

import matplotlib.pyplot as plt
def plot_charts(n_epochs, model_results):
  epochs = range(n_epochs)
  train_loss = model_results['train_loss']
  test_loss = model_results['test_loss']
  train_acc = model_results['train_acc']
  test_acc = model_results['test_acc']
  plt.figure(figsize=(12,6))
  # Chart 1
  plt.subplot(1,2,1)
  plt.plot(epochs, train_loss, label = 'train_loss')
  plt.plot(epochs, test_loss, label = 'test_loss')
  plt.legend();
  # Chart 2
  plt.subplot(1,2,2)
  plt.plot(epochs, train_acc, label = 'train_acc')
  plt.plot(epochs, test_acc, label = 'test_acc')
  plt.legend();

plot_charts(n_epochs = 10,
            model_results = model_1_results)

"""If we train for longer, it looks like we get slightly lower loss and potentially higher accuracy but our model starts to look like it overfits if we train for too long.

Potentially data augmentation or a learning rate decay (lowering the learning rate over time) can help to prevent overfitting.

## 5. Train the model from section 4 above with more data, say 20% of the images from Food101 of Pizza, Steak and Sushi images.
* You can find the [20% Pizza, Steak, Sushi dataset](https://github.com/mrdbourke/pytorch-deep-learning/blob/main/data/pizza_steak_sushi_20_percent.zip) on the course GitHub. It was created with the notebook [`extras/04_custom_data_creation.ipynb`](https://github.com/mrdbourke/pytorch-deep-learning/blob/main/extras/04_custom_data_creation.ipynb).
"""

import os
import requests
from pathlib import Path
import zipfile
data_path = Path('data/')
image_path = data_path/'pizza_steak_sushi_20_percent'
image_path_zip = data_path/'pizza_steak_sushi_20_percent.zip'
if image_path.is_dir():
  print(f'{image_path} already exist. Skipping the download.')
else:
  print(f'{image_path} does not exist. Create a now one...')
  image_path.mkdir(parents = True, exist_ok = True)

  with open(image_path_zip, 'wb') as f:
    request = requests.get('https://github.com/mrdbourke/pytorch-deep-learning/raw/main/data/pizza_steak_sushi_20_percent.zip')
    print(f'Download {image_path_zip}')
    f.write(request.content)
  with zipfile.ZipFile(image_path_zip, 'r') as zip_ref:
    zip_ref.extractall(image_path)
  os.remove(image_path_zip)
train_dir_20_percent = image_path/'train'
test_dir_20_percent  = image_path/'test'

# Create training and testing DataLoader's as well as get a list of class names
train_dataloader_20_percent, test_dataloader_20_percent, class_names = data_setup.create_dataloaders( train_dir=train_dir_20_percent,
                                                                                                     test_dir=test_dir_20_percent,
                                                                                                     transform=simple_transform, # resize, convert images to between 0 & 1 and normalize them
                                                                                                     batch_size=32) # set mini-batch size to 32
train_dataloader_20_percent, test_dataloader_20_percent, class_names

simple_transform = transforms.Compose([
    transforms.Resize(size=(224,224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485,0.456,0.406],
                         std=[0.229,0.224,0.225])
])
simple_transform

len(train_dataloader_20_percent), len(test_dataloader_20_percent)

"""### Get a pretrained model"""

model_2 = torchvision.models.efficientnet_b0(pretrained = True).to(device)
# Freeze all base layers
for param in model_2.features.parameters():
  param.requires_grad = False
# Change the classifier head
model_2.classifier = nn.Sequential(
    nn.Dropout(p=0.2, inplace=True),
    nn.Linear(in_features = 1280, out_features = 3, bias = True)
).to(device)

"""### Train a model with 20% of the data"""

# Set up a loss function and an optimizer
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(params = model_2.parameters(), lr = 0.001)
# Train model_2
model_2_results = engine.train(model = model_2,
                               train_dataloader = train_dataloader_20_percent,
                               test_dataloader = test_dataloader_20_percent,
                               loss_fn = loss_fn,
                               optimizer = optimizer,
                               epochs = 5,
                               device = device
                               )

plot_charts(n_epochs = 5,
            model_results = model_2_results)

print(f'max loss : {max(model_1_results['test_loss'])} | min loss : {min(model_1_results['test_loss'])}')

print(f'max loss : {max(model_2_results['test_loss'])} | min loss : {min(model_2_results['test_loss'])}')

"""## 6. Try a different model from [`torchvision.models`](https://pytorch.org/vision/stable/models.html) on the Pizza, Steak, Sushi data, how does this model perform?
* You'll have to change the size of the classifier layer to suit our problem.
* You may want to try an EfficientNet with a higher number than our B0, perhaps `torchvision.models.efficientnet_b2()`?
"""

# Create a transform to transform the data
from torchvision import transforms
effnet_b2_transform = transforms.Compose([
    transforms.Resize(size=(288,288)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225])
])

# Import the data
train_dataloader_effnet_b2, test_dataloader_effnet_b2, class_names = data_setup.create_dataloaders(train_dir = train_dir,
                                                                                                   test_dir = test_dir,
                                                                                                   batch_size = 32,
                                                                                                   transform = effnet_b2_transform)
train_dataloader_effnet_b2, test_dataloader_effnet_b2, class_names

model_3 = torchvision.models.efficientnet_b2(pretrained = True).to(device)
# Freeze all base layers
for param in model_3.features.parameters():
  param.requires_grad = False
# Change the classifier head
torch.manual_seed(42)
model_3.classifier = nn.Sequential(
    nn.Dropout(p=0.3, inplace=True),
    nn.Linear(in_features=1408, out_features=len(class_names), bias=True)
).to(device)
# model_3 summary
summary(model = model_3,
        input_size = [32,3,288,288],
        col_names = ['input_size', 'output_size', 'trainable'])

# model_2 summary
summary(model = model_2,
        input_size = [32,3,224,224],
        col_names = ['input_size', 'output_size', 'trainable'])

"""Which one did the best?

Experiments:
* model_0 = 10% data, effnet_b0, 5 epochs
* model_1 = 10% data, effnet_b0, 10 epochs (double training time)
* model_2 = 20% data, effnet_b0, 5 epochs (double data)
* model_3 = 10% data, effnet_b2, 5 epochs (double model parameters)
"""

# Set up loss function and optimizer
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(params = model_3.parameters(), lr = 0.001)
# Train the model
start_train = timer()
model_3_results = engine.train(model = model_3,
                               train_dataloader = train_dataloader_effnet_b2,
                               test_dataloader = test_dataloader_effnet_b2,
                               optimizer = optimizer,
                               loss_fn = loss_fn,
                               epochs = 5,
                               device = device)
end_train = timer()
train_time = end_train - start_train
print(f'The model was training for {train_time // 60} min and {train_time % 60} sec.')

max(model_0_results['test_loss']), min(model_0_results['test_loss'])

max(model_1_results['test_loss']), min(model_1_results['test_loss'])

max(model_2_results['test_loss']), min(model_2_results['test_loss'])

max(model_3_results['test_loss']), min(model_3_results['test_loss'])



